language: php
php:
  - '7.0'

sudo: required

services:
  - docker

before_script:
  - cp .env.example .env
  - docker-compose build > /dev/null
  - docker-compose run webapp composer install --no-interaction

script:
  - make test
