language: php
php:
  - '7.0'

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

before_script:
  - cp .env.example .env
  - docker-compose build > /dev/null
  - docker-compose run webapp composer install --no-interaction
  - docker-compose run webapp php artisan migrate
  - docker-compose run webapp php artisan db:searchindex
  - docker-compose run webapp php artisan db:seed

script:
  - make test-ci

after_script:
  - docker-compose run -e CODACY_PROJECT_TOKEN=4171a045b65d4b4a9a89686b66720e32 webapp vendor/bin/codacycoverage clover ./.coverage/coverage-clover.xml
