language: php
php:
  - '7.0'

sudo: required

services:
  - docker

before_script:
  - cp .env.example .env
  - docker-compose build > /dev/null
  - docker-compose run webapp composer install --no-interaction
  - docker-compose run webapp php artisan migrate
  - docker-compose run webapp php artisan db:searchindex
  - docker-compose run webapp php artisan db:seed

script:
  - make test-ci

after_script:
  - docker-compose run -e CODACY_PROJECT_TOKEN=4171a045b65d4b4a9a89686b66720e32 webapp vendor/bin/codacycoverage clover ./.coverage/coverage-clover.xml
