webapp:
  build: .
  volumes:
    - .:/var/www/html
    - ~/.config/psysh:/root/.config/psysh
  ports:
    - "8000:80"
  links:
    - mongo
    - elastic
    - redis
  environment:
    DB_HOST: mongo
scheduled:
  build: .
  volumes_from:
    - webapp
  links:
    - mongo
    - elastic
    - redis
  environment:
    DB_HOST: mongo
  command: cron -f
mongodata:
  image: mongo:3.2
  volumes:
    - /mnt/sda1/data/mongo/db:/data/db
  command: --break-mongo
mongo:
  image: mongo:3.2
  volumes_from:
    - mongodata
  expose:
    - "27017-27019"
    - "28017"
  command: --smallfiles --rest
elastic:
  image: "elasticsearch:2.3"
  ports:
    - "9200"
    - "9300"
  volumes:
    - "/mnt/sda1/data/elastic/logs:/usr/share/elasticsearch/logs"
    - "/mnt/sda1/data/elastic/data:/usr/share/elasticsearch/data"
redis:
    image: redis:alpine
    ports:
      - "36379:6379"
